### ISSUE TITLE
Tracking issue for stuff related to next release

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1445]
This is not exhaustive, but instead of using milestones, I'm going to use this list to track stuff I want to remember:
- [x] sign windows app (#1403)
- [ ] fix unicode listener input bug (#1382)
- [ ] fix windows gradient text bug (#152 and #1397)
- [ ] fix windows rendering on retina displays (#1405)
- [ ] fix windows unicode text rendering (#860)
- [x] fix windows ssl certificate checking (#1092)
- [x] fix `get-ifaddrs` compile bug (#1370)
- [x] fix universal comments (#737 and #1243)
- [x] fix (compile?) bug in pegs (#23)
- [x] fix string end-of-line continuation (#1242)
- [x] fix browser search text field to show gray "Search" on it with no contents not `label-on-left`
- [x] rename `unordered-set` back to `set` (need a good way to disambiguate w/ `namespaces:set`)
- [ ] resolve accessor conflict with `change-at`, `change-nth`, `change-global`
- [ ] resolve lua-style long strings vs. triple-quote strings (right now we have neither)
- [x] move vocabs from `unmaintained` back to `extra` (#1448)
- [ ] cleanup "variable get" syntax (#1447)
- [ ] cleanup tuple literals (#1449)
- [ ] cleanup `FUNCTOR:` syntax (#1435)
- [ ] merge `modern.parser` and refactoring tools
  - probably a version that can lex/parse all code, but doesn't replace `parser` yet?

And after we release 0.98, we should update this homebrew-cask (https://github.com/caskroom/homebrew-cask/issues/7766).

**Comment by catb0t** [comment]
so the `modern.harvey` branch or some part of it has to be merged before #1435, #1447, and #1449 can be resolved like you wanted for 0.98. maybe these could be left as it is for now until 0.99, unless @erg will make the modern code mergeable by the time (or if ever) #1382 #1397 #1405 #860 are fixed?

**Comment by mrjbq7** [comment]
Definitely not merging that branch until after release.  It's got some wild ideas that are gonna be awesome once they start working but would be unnecessary instability prior to a good 0.98 release.

**Comment by catb0t** [comment]
from the discussions on the parser issues, it seems to me that 
* lua-style long strings vs. triple-quote strings
* #1447 
* #1449
* #1435

would most hopefully be fixed by the new parser, but the new parser isn't being merged until after 0.98, so these goals should be ignored on the immediate roadmap?

**Comment by mrjbq7** [comment]
Yep, probably so.

Although "triple-quote strings" we used to have in 0.97 and could re-add
them for 0.98.

**Comment by erg** [comment]
I'm slightly negative about adding back triple-quote strings, but if we do, please don't use them. ✌️

**Comment by erg** [comment]
We released! Closing this...the github bug tracker can handle .99 goals.
