### ISSUE TITLE
Look at slava's last todo list on the concatenative wiki and see what we have to do still

### ISSUE THREAD

**Issue by erg** [factor/factor#2676]
https://concatenative.org/wiki/view/Factor/To%20do

- [ ] checkboxes here?

**Comment by razetime** [comment]
# Regex
- [ ]  Group capture
- [ ] Possessive and reluctant modifiers for star
- [ ] A Ragel-like system
- [ ] An EBNF-like system for regular languages, maybe using Dube and Feeley's algorithm for generating a parse tree for regexps
- [ ] Better Unicode support (level 2, hopefully)
